# Константы для удобства настроек.
substitutions:
  name: esp-pump-r2
  friendly_name: pump-r2
  project: Sonoff Mini R2
  sensor_gpio: GPIO04 #
  relay_gpio: GPIO12
  prefix: "esphome/${name}"

# Описание платы, в моём реле стоит esp8285.
esphome:
  name: ${name}
  platform: ESP8266
  board: esp8285

# Отключаем сторожевой таймер, чтобы контроллер
# реле не перезапускадся каждые 15 минут из-за того,
# что нет подключений по API
api:
  reboot_timeout: 0s

# Чтобы обновлять прошивку по воздуху.
ota:
  password: "ваш_пароль_ota"

# Подключение к Wi-Fi
wifi:
  ssid: "WB-LAB"
  password: "ваш_пароль_wifi"
  ap:
    ssid: Fallback ${name}
    password: "ваш_пароль_резервная_точка_доступа"

# Если не получится подключиться к Wi-Fi,
# то поднять свой веб-интерфейс с логином
# и паролем указанным выше в разделе «ap:».
captive_portal:

# Подключение к MQTT
mqtt:
  broker: wirenboard-ascmdm6q.local
  port: 1883
  username: ''
  password: ''
  discovery: false
  id: mqtt_client
  topic_prefix: "${prefix}"
# Сообщения с текущим статусом устройства
  birth_message:
      topic: "${prefix}/text_sensor/status/state"
      payload: online

  will_message:
      topic: "${prefix}/text_sensor/status/state"
      payload: offline

  shutdown_message :
      topic: "${prefix}/text_sensor/status/state"
      payload: shutdown

# Датчик расхода воды
sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s

  - platform: uptime
    name: "Uptime"
    update_interval: 5s

  - platform: pulse_counter
    name: "Flow Sensor"
    id: flow_sensor
    pin:
      number: $sensor_gpio
      mode: INPUT_PULLUP
    unit_of_measurement: "impulses"
    update_interval: 500ms
# Если датчик расхода присылает больше 100 имульсов,
# то включаем реле, иначе — выключаем.
    on_value:
      if:
        condition:
          sensor.in_range:
            id: flow_sensor
            above: 100.0
        then:
          - output.turn_on: pump_relay
        else:
          - output.turn_off: pump_relay

# Состояние выхода реле, для MQTT
binary_sensor:
  - platform: gpio
    pin: $relay_gpio
    name: "State"
    id: pump_state

# Выход реле
output:
  - platform: gpio
    id: pump_relay
    pin: $relay_gpio
